### ISSUE TITLE
cargo liquid build 出错

### ISSUE THREAD

**Issue by 2473o** [WeBankBlockchain/liquid#42]
如下所示:
```
root@119bcf939882:~/hello_world# cargo liquid build
[1/4] d(・ω・d) Collecting crate metadata
[2/4] (∫・ω・)∫ Building cargo project
[3/4] ∇(・ω・∇) Optimizing Wasm bytecode
ERROR: Loading original wasm file '/root/hello_world/target/wasm32-unknown-unknown/release/deps/hello_world.wasm'

Caused by:
    Unknown opcode 192
```

修改内容：
```
注释 
liquid-efa081b34c5597c9/c678d95/primitives/src/types/fixed_size_bytes.rs
218 | | seq!(N in 1..=32 {
219 | |     impl_bytes_from_bytes!(
220 | |         #(Bytes#N as Bytes{+1#N => 32},)*
221 | |     );
222 | | });
```

版本
```
rustc 1.70.0-nightly (84dd17b56 2023-04-14)
cargo 1.70.0-nightly (84b7041fd 2023-04-13)
```

toolchain 
```
nightly-2023-04-15-x86_64-unknown-linux-gnu (default)
```

**Comment by 2473o** [comment]
注释是因为测试不通过
```
root@119bcf939882:~/hello_world# cargo test
……
error: proc macro panicked
   --> /root/.cargo/git/checkouts/liquid-efa081b34c5597c9/c678d95/primitives/src/types/fixed_size_bytes.rs:218:2
    |
218 | /  seq!(N in 1..=32 {
219 | |      impl_bytes_from_bytes!(
220 | |          #(Bytes#N as Bytes{+1#N => 32},)*
221 | |     );
222 | | });
    | |__^
    |
    = help: message: called `Option::unwrap()` on a `None` value

error: could not compile `liquid_primitives` (lib) due to previous error
```

**Comment by miao1108** [comment]
请问您解决这个问题了嘛，如果解决啦是怎么解决的呢

**Comment by 2473o** [comment]
> 请问您解决这个问题了嘛，如果解决啦是怎么解决的呢

没，建议你去官方群里问问小助手

**Comment by miao1108** [comment]
> > 请问您解决这个问题了嘛，如果解决啦是怎么解决的呢
> 
> 没，建议你去官方群里问问小助手

好滴，谢谢你哇

**Comment by 2473o** [comment]
关联问题 https://github.com/WeBankBlockchain/cargo-liquid/issues/28#issuecomment-2026866350

**Comment by bxq2011hust** [comment]
https://github.com/rust-lang/rust/issues/109807
https://github.com/CosmWasm/cosmwasm/issues/1727
应该是1.70+的工具链生成的wasm二进制带了mvp以外的opcode

**Comment by bxq2011hust** [comment]
> [rust-lang/rust#109807](https://github.com/rust-lang/rust/issues/109807) [CosmWasm/cosmwasm#1727](https://github.com/CosmWasm/cosmwasm/issues/1727) 应该是1.70+的工具链生成的wasm二进制带了mvp以外的opcode

可以尝试按装下面我修改后的cargo-liquid工具，然后再`cargo liquid build`试试
```bash
cargo install --git https://github.com/bxq2011hust/cargo-liquid --branch main --force
```

**Comment by 2473o** [comment]
我的环境是 ubuntu 22.04 server LTS，这个仓库的Binaryen wasm-opt 不带`--signext-lowering`， 可以从[binaryen](https://github.com/WebAssembly/binaryen)下载
还有就是修改下`template`下的rust-toolchain.toml ，内容还是`channel = "nightly-2023-01-03"`🙂

> > [rust-lang/rust#109807](https://github.com/rust-lang/rust/issues/109807) [CosmWasm/cosmwasm#1727](https://github.com/CosmWasm/cosmwasm/issues/1727) 应该是1.70+的工具链生成的wasm二进制带了mvp以外的opcode
> 
> 可以尝试按装下面我修改后的cargo-liquid工具，然后再`cargo liquid build`试试
> 
> ```shell
> cargo install --git https://github.com/bxq2011hust/cargo-liquid --branch main --force
> ```
